Program myProgCorrect

var x : int
var y : float
var z : int
var A : float
var B : float
var C : float
var D : float


main()
{
    x = y-1 * (2.4+400)-3 / 2*y
    while ( z>2*x) then {
	  z = z-2*x
        write(z)
    }    
    write(x)
    y = read()
    write("hola")
    y = 2+x*y
    when (A + B < C) then
    {
        A = B + C
        while (A > B + C) then
        {
            A = A - 1
        }
    } else
    {
        while (B > C + D) then
        {
            A = B + C * D
            B = A-D
        }
    }
}